name: Deploy Compare Page

on:
  push:
    branches:
      - main
      - stage
    paths:
      - apps/compare/**
      - packages/**
      - .github/workflows/compare.yaml
  pull_request:
    branches:
      - main
      - stage
    paths:
      - apps/compare/**
      - packages/**
      - .github/workflows/compare.yaml

  workflow_dispatch:

env:
  NODE_VERSION: '24.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: NPM Install
        run: npm i

      - name: Check
        run: npm run check

      - name: Build
        run: npx turbo run @lcax/compare#build
        env:
          VITE_UMAMI_ID: ${{ secrets.COMPARE_UMAMI_ID }}

      - name: Upload artifact for deployment job
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: ./apps/compare/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: app

      - name: Install s5cmd
        run: |
          curl -L https://github.com/peak/s5cmd/releases/download/v2.3.0/s5cmd_2.3.0_Linux-64bit.tar.gz \
            | tar xz
          sudo mv s5cmd /usr/local/bin/

      - name: Upload to Bundle
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          AWS_REGION: us-east-1
        run: s5cmd --endpoint-url https://minio.chrk.site cp "./*" "s3://bundles/lcax/${{ github.ref_name }}/compare/"
